### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by KALPIT2603** [zeeshanallrounder/Android-Studio-Ecommerce-App#2]
I have creted amin manually on firebase. and trying to log in as admin but is not working. it always goes to the mainactivity and crashes. can youu please solve this?

![image](https://user-images.githubusercontent.com/40545146/86840729-b5870500-c0c0-11ea-9c5b-62405cd1adcd.png)

**Comment by zee-shan000** [comment]
Due to sume Firebase Connectivity...Check the connection...Connect Firebase with App through Androidstudio
